# Generated by Django 4.0.1 on 2022-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_orders_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
